//! Render synthetic `resolv.conf` and `/etc/hosts` content from profile
//! network settings. Content generation is platform-agnostic; the caller
//! (per-platform runner) decides whether to bind-mount or sidecar-expose.

use crate::config::Network;

/// Returns `Some(content)` if the profile overrides DNS. `None` means no
/// override — leave the system resolver alone.
pub fn resolv_conf(net: &Network) -> Option<String> {
    let dns = &net.dns;
    if dns.servers.is_empty() && dns.search.is_empty() && dns.options.is_empty() {
        return None;
    }
    let mut s = String::new();
    s.push_str("# generated by sandkasten\n");
    for srv in &dns.servers {
        s.push_str(&format!("nameserver {srv}\n"));
    }
    if !dns.search.is_empty() {
        s.push_str("search ");
        s.push_str(&dns.search.join(" "));
        s.push('\n');
    }
    for opt in &dns.options {
        s.push_str(&format!("options {opt}\n"));
    }
    Some(s)
}

/// Returns `Some(content)` with extra /etc/hosts entries to merge with the
/// default loopback lines, or `None` if no overrides are configured.
pub fn hosts_extra(net: &Network) -> Option<String> {
    if net.hosts_entries.is_empty() {
        return None;
    }
    let mut s = String::new();
    // Standard loopback entries so basic name resolution still works.
    s.push_str("127.0.0.1  localhost\n");
    s.push_str("::1        localhost\n");
    s.push_str("\n# sandkasten overrides\n");
    for (host, ip) in &net.hosts_entries {
        // Very light validation — reject whitespace in either field.
        if host.chars().any(char::is_whitespace) || ip.chars().any(char::is_whitespace) {
            continue;
        }
        s.push_str(&format!("{ip}  {host}\n"));
    }
    Some(s)
}
